import os, sys, platform, json, subprocess, time, urllib.request, zipfile, shutil, stat

# ==============================================================================
# 🏭 BASIC v2.1: The Self-Sufficient Factory
# Feature: Tuner + Self-Repair Engine + Builder (English Version)
# ==============================================================================

ROOT = os.path.dirname(os.path.abspath(__file__))
CONFIG_PATH = os.path.join(ROOT, "config.json")
IS_MOBILE = 'termux' in str(os.environ) or 'android' in str(os.environ)

# [SYSTEM UTILS] OS Detection & Auto-Recovery Logic
class SystemUtils:
    @staticmethod
    def get_binary_name():
        sys_os = platform.system().lower()
        if 'windows' in sys_os: return "llama-cli.exe"
        return "llama-cli"

    @staticmethod
    def get_driver_path():
        return os.path.join(ROOT, 'drivers', SystemUtils.get_binary_name())

    @staticmethod
    def download_engine():
        print(" [SYSTEM] Engine binary missing. Initiating Auto-Recovery...")
        sys_os = platform.system().lower()
        URL_BASE = "https://github.com/ggerganov/llama.cpp/releases/download/b4604/"
        
        if 'windows' in sys_os: target = URL_BASE + "llama-b4604-bin-win-avx-x64.zip"
        elif 'darwin' in sys_os: target = URL_BASE + "llama-b4604-bin-macos-arm64.zip"
        else: target = URL_BASE + "llama-b4604-bin-linux-x64.zip"

        drivers_dir = os.path.join(ROOT, 'drivers')
        if not os.path.exists(drivers_dir): os.makedirs(drivers_dir)
        
        zip_path = os.path.join(drivers_dir, "temp_engine.zip")
        try:
            import ssl
            ssl._create_default_https_context = ssl._create_unverified_context
            print(f"   └─ Downloading from source...")
            urllib.request.urlretrieve(target, zip_path)
            
            with zipfile.ZipFile(zip_path, 'r') as z:
                for n in z.namelist():
                    if 'llama-cli' in n and not n.endswith('/'):
                        with z.open(n) as s, open(SystemUtils.get_driver_path(), "wb") as t:
                            shutil.copyfileobj(s, t)
            
            if 'windows' not in sys_os:
                st = os.stat(SystemUtils.get_driver_path())
                os.chmod(SystemUtils.get_driver_path(), st.st_mode | stat.S_IEXEC)
            print(" [SYSTEM] Engine Recovery Complete.")
            return True
        except Exception as e:
            print(f" [ERROR] Recovery Failed: {e}")
            return False
        finally:
            if os.path.exists(zip_path): os.remove(zip_path)

# [CONFIG] Load Configuration
def load_config():
    if not os.path.exists(CONFIG_PATH):
        # Default fallback
        return {"engine": {"threads": 4, "gpu_layers": 99, "ctx_size": 4096, "flash_attn": False}}
    with open(CONFIG_PATH, 'r', encoding='utf-8') as f:
        return json.load(f)

def save_config(cfg):
    with open(CONFIG_PATH, 'w', encoding='utf-8') as f:
        json.dump(cfg, f, indent=4)

GLOBAL_CFG = load_config()
ENGINE_CFG = GLOBAL_CFG.get('engine', {})

# ==============================================================================
# 🏗️ BUILDER (Factory Arm)
# ==============================================================================
class Builder:
    def __init__(self):
        self.dist_dir = os.path.join(ROOT, "dist")
        
    def build_standalone(self):
        print("\n" + "="*40)
        print(" 🏭 BASIC FACTORY // ASSEMBLING CHASSIS")
        print("="*40)
        
        if not os.path.exists(self.dist_dir): os.makedirs(self.dist_dir)
        target = os.path.join(self.dist_dir, "void_standalone.py")
        
        # Self-Reading (Quine)
        with open(__file__, 'r', encoding='utf-8') as f:
            code = f.read()
            
        header = '"""\n GENERATED BY BASIC FACTORY\n Type: Standalone Self-Repair Chassis\n"""\n'
        
        with open(target, 'w', encoding='utf-8') as f:
            f.write(header + code)
            
        size = os.path.getsize(target) / 1024
        print(f" [SUCCESS] Built: {target} ({size:.1f} KB)")
        print(" [NOTE] This file can heal itself (auto-download engine) if moved.")
        print("="*40)
        input(" Press Enter to return...")

# ==============================================================================
# 🎛️ TUNER (Control Panel)
# ==============================================================================
class Tuner:
    def __init__(self):
        self.builder = Builder()
        self.dashboard()

    def clear(self):
        os.system("clear" if IS_MOBILE or os.name!='nt' else "cls")

    def dashboard(self):
        while True:
            self.clear()
            print(" ┌──────────────────────────────────────────────────┐")
            print(f" │ 🎛️  BASIC v2.1 // SELF-SUFFICIENT EDITION         │")
            print(" ├──────────────────────────────────────────────────┤")
            print(f" │ [1] CPU Threads   : {ENGINE_CFG.get('threads', 4)}")
            print(f" │ [2] GPU Layers    : {ENGINE_CFG.get('gpu_layers', 0)}")
            print(f" │ [3] Context Size  : {ENGINE_CFG.get('ctx_size', 2048)}")
            print(" ├──────────────────────────────────────────────────┤")
            print(" │ [A] Auto-Optimize (Hardware Scan)                │")
            print(" │ [B] BUILD STANDALONE (Create Copy)               │")
            print(" │ [S] START ENGINE (Ignition)                      │")
            print(" │ [Q] Quit                                         │")
            print(" └──────────────────────────────────────────────────┘")
            
            cmd = input(" 🔧 Command > ").lower().strip()
            
            if cmd == 's': 
                save_config(GLOBAL_CFG)
                try: Engine().run()
                except KeyboardInterrupt: pass
                except Exception as e: print(f"\n [ERROR] {e}"); time.sleep(2)
            elif cmd == 'q': sys.exit(0)
            elif cmd == 'b': self.builder.build_standalone()
            elif cmd == 'a': self.auto_tune()
            elif cmd == '1': self.set_val("threads")
            elif cmd == '2': self.set_val("gpu_layers")
            elif cmd == '3': self.set_val("ctx_size")

    def set_val(self, key):
        try:
            val = input(f" Set {key} value: ")
            if val.isdigit(): ENGINE_CFG[key] = int(val)
        except: pass

    def auto_tune(self):
        print(" [!] Scanning Topology...")
        cpu = os.cpu_count() or 4
        if IS_MOBILE:
            ENGINE_CFG['threads'] = max(2, cpu - 2)
            ENGINE_CFG['ctx_size'] = 2048
        else:
            ENGINE_CFG['threads'] = cpu
            ENGINE_CFG['ctx_size'] = 8192
        print(" [!] Optimization Applied.")
        time.sleep(0.5)

# ==============================================================================
# 🚀 ENGINE (Core)
# ==============================================================================
class Engine:
    def __init__(self):
        self.root = ROOT
        
    def run(self):
        # 1. Self-Diagnostics & Recovery
        driver = SystemUtils.get_driver_path()
        if not os.path.exists(driver):
            if not SystemUtils.download_engine():
                input(" [!] Engine Setup Failed. Press Enter to return...")
                return

        # 2. Model Scan
        mdir = os.path.join(self.root, 'models')
        if not os.path.exists(mdir): os.makedirs(mdir)
        
        models = [f for f in os.listdir(mdir) if f.endswith('.gguf')]
        if not models:
            print("\n [!] No .gguf models found in /models")
            print(" [!] Please place a model file to proceed.")
            input(" Press Enter to return...")
            return
        
        model = os.path.join(mdir, models[0])

        # 3. Ignition
        cmd = [
            driver, "-m", model,
            "-t", str(ENGINE_CFG.get('threads', 4)),
            "-ngl", str(ENGINE_CFG.get('gpu_layers', 0)),
            "-c", str(ENGINE_CFG.get('ctx_size', 2048)),
            "-cnv", "--log-disable",
            "-p", "System: You are BASIC AI.\nUser: Ready.\nAI: Standing by.\nUser: "
        ]
        
        print(f"\n [🚀] Ignition: {models[0]}")
        print(" [!] Press Ctrl+C to return to Dashboard.\n")
        subprocess.run(cmd)

if __name__ == "__main__":
    try:
        Tuner()
    except KeyboardInterrupt:
        print("\n [!] Force Shutdown.")
